name: Generate Snake Animation

on:
  # Se ejecuta automáticamente cada 24 horas
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  
  # Se ejecuta cada vez que haces un push a la rama main
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Genera la serpiente a partir de tus contribuciones
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # Sube los archivos generados a una rama llamada 'output'
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
